# Generated by Django 4.2.25 on 2025-11-14 15:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Este nombre de usuario ya existe.'}, help_text='Requerido. 150 caracteres o menos. Letras, números y caracteres especiales permitidos.', max_length=150, unique=True, verbose_name='username')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FormularioAtencion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REQUIERE_MODIFICACION', 'Requiere Modificacion'), ('MODIFICADO', 'Modificado'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=25)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre_paciente', models.CharField(blank=True, max_length=200, null=True)),
                ('rut_paciente', models.CharField(blank=True, max_length=12, null=True)),
                ('edad_paciente', models.IntegerField(blank=True, null=True)),
                ('unidad_edad_paciente', models.CharField(default='Años', max_length=10)),
                ('sexo_paciente', models.CharField(blank=True, max_length=10, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('saturacion_oxigeno', models.IntegerField(blank=True, null=True)),
                ('glasgow', models.IntegerField(blank=True, null=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('tratamiento_administrado', models.TextField(blank=True, null=True)),
                ('solicitudes_paciente', models.TextField(blank=True, null=True)),
                ('triage', models.CharField(default='Verde', max_length=10)),
                ('instrucciones_recepcion', models.TextField(blank=True, null=True)),
                ('eta_fecha', models.DateField(blank=True, null=True)),
                ('eta_hora', models.TimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_creados', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_en_revision', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='anamnesis.formularioatencion')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
