# Generated by Django 4.2.25 on 2025-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioatencion',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
