# Generated by Django 4.2.25 on 2025-11-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0002_formularioatencion_aprobado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioatencion',
            name='accidente_laboral',
            field=models.BooleanField(default=False, verbose_name='Accidente Laboral'),
        ),
        migrations.AddField(
            model_name='formularioatencion',
            name='fio2',
            field=models.IntegerField(blank=True, null=True, verbose_name='FiO2 (%)'),
        ),
        migrations.AddField(
            model_name='formularioatencion',
            name='funcionalidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Funcionalidad (VGI + EVF)'),
        ),
        migrations.AddField(
            model_name='formularioatencion',
            name='llene_capilar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Llene Capilar'),
        ),
        migrations.AddField(
            model_name='formularioatencion',
            name='musculatura_accesoria',
            field=models.BooleanField(default=False, verbose_name='Uso Musculatura Accesoria'),
        ),
        migrations.AddField(
            model_name='formularioatencion',
            name='prestacion_requerida',
            field=models.TextField(blank=True, null=True, verbose_name='Prestación Requerida'),
        ),
        migrations.AddField(
            model_name='formularioatencion',
            name='prevision',
            field=models.CharField(blank=True, choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre'), ('DIPRECA', 'Dipreca'), ('PARTICULAR', 'Particular'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Previsión'),
        ),
        migrations.AddField(
            model_name='formularioatencion',
            name='score_mottling',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Score Mottling'),
        ),
    ]
